'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import TrackList from '@/components/TrackList';
import TunePanel from '@/components/TunePanel';
import type { PlaylistData, ChatMessage, AudioFeatureTargets } from '@/lib/types';

export default function PlaylistPage() {
  const router = useRouter();
  const [data, setData] = useState<PlaylistData | null>(null);
  const [chatHistory, setChatHistory] = useState<ChatMessage[]>([]);
  const [isTuning, setIsTuning] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [savedUrl, setSavedUrl] = useState<string | null>(null);
  const [saveError, setSaveError] = useState<{ message: string; isRestriction: boolean } | null>(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    const raw = sessionStorage.getItem('brew_playlist');
    if (!raw) { router.replace('/'); return; }
    try {
      const parsed = JSON.parse(raw) as PlaylistData;
      setData(parsed);
      if (parsed.reasoning) {
        setChatHistory([{ role: 'assistant', text: parsed.reasoning }]);
      }
    } catch {
      router.replace('/');
    }
  }, [router]);

  async function handleTune(message: string | null, audioTargets: AudioFeatureTargets | null) {
    if (!data || isTuning) return;
    setIsTuning(true);

    const userText = message ?? formatTargets(audioTargets);
    setChatHistory((prev) => [...prev, { role: 'user', text: userText }]);

    try {
      const res = await fetch('/api/tune', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          currentTracks: data.tracks,
          message,
          audioTargets,
          audioFeatures: data.audioFeatures,
          count: data.count ?? 15,
        }),
      });
      const result = await res.json();
      if (!res.ok) throw new Error(result.error ?? 'Tune failed');

      const updated: PlaylistData = {
        ...data,
        tracks: result.tracks,
        audioFeatures: result.audioFeatures,
        reasoning: result.reasoning,
      };
      setData(updated);
      sessionStorage.setItem('brew_playlist', JSON.stringify(updated));
      setChatHistory((prev) => [...prev, { role: 'assistant', text: result.reasoning }]);
    } catch (err) {
      setChatHistory((prev) => [...prev, { role: 'assistant', text: `Something went wrong: ${err}` }]);
    } finally {
      setIsTuning(false);
    }
  }

  async function handleSave() {
    if (!data || isSaving) return;
    setIsSaving(true);
    setSaveError(null);
    try {
      const res = await fetch('/api/playlist/save', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: `Brew: ${data.prompt}`,
          description: `Generated by Brew My Spot — "${data.prompt}"`,
          trackIds: data.tracks.map((t) => t.id),
        }),
      });
      const result = await res.json();
      if (!res.ok) {
        setSaveError({ message: result.error ?? 'Save failed', isRestriction: !!result.isRestriction });
        return;
      }
      setSavedUrl(result.playlistUrl);
    } catch (err) {
      setSaveError({ message: String(err), isRestriction: false });
    } finally {
      setIsSaving(false);
    }
  }

  function handleRemove(trackId: string) {
    if (!data) return;
    const updated: PlaylistData = {
      ...data,
      tracks: data.tracks.filter((t) => t.id !== trackId),
    };
    setData(updated);
    sessionStorage.setItem('brew_playlist', JSON.stringify(updated));
  }

  function handleCopyLinks() {
    if (!data) return;
    const links = data.tracks.map((t) => t.external_urls.spotify).join('\n');
    navigator.clipboard.writeText(links).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  if (!data) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#0d0d0d]">
        <div className="w-8 h-8 border-2 border-[#1db954] border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  return (
    <div className="h-screen flex flex-col bg-[#0d0d0d] overflow-hidden">
      {/* Header */}
      <header className="flex items-center justify-between px-5 py-3 border-b border-zinc-800 shrink-0">
        <div className="flex items-center gap-3 min-w-0">
          <button
            onClick={() => router.push('/')}
            className="text-zinc-400 hover:text-white transition-colors text-sm shrink-0 border border-zinc-700 hover:border-zinc-500 rounded-full px-3 py-1"
          >
            ← New
          </button>
          <div className="min-w-0 border-l border-zinc-800 pl-3">
            <span className="text-white font-semibold text-sm truncate block">{data.prompt}</span>
            <span className="text-zinc-600 text-xs">{data.tracks.length} tracks</span>
          </div>
        </div>
        <div className="flex items-center gap-2 shrink-0">
          {savedUrl ? (
            <a
              href={savedUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1 bg-[#1db954] text-black font-semibold px-4 py-2 rounded-full text-sm hover:bg-[#1ed760] transition-colors"
            >
              Open in Spotify ↗
            </a>
          ) : saveError?.isRestriction ? (
            <div className="flex items-center gap-2">
              <span className="text-zinc-500 text-xs max-w-[200px] leading-tight">
                Spotify API restriction — click tracks to open each in Spotify.
              </span>
              <button
                onClick={handleCopyLinks}
                className="bg-zinc-800 hover:bg-zinc-700 border border-zinc-700 text-zinc-300 font-medium px-3 py-1.5 rounded-full text-xs transition-colors whitespace-nowrap"
              >
                {copied ? 'Copied!' : 'Copy links'}
              </button>
              <button
                onClick={handleSave}
                disabled={isSaving}
                className="bg-zinc-800 hover:bg-zinc-700 border border-zinc-700 text-zinc-400 font-medium px-3 py-1.5 rounded-full text-xs transition-colors whitespace-nowrap disabled:cursor-not-allowed"
              >
                Retry
              </button>
            </div>
          ) : (
            <>
              {saveError && <span className="text-red-400 text-xs max-w-[160px] leading-tight">{saveError.message}</span>}
              <button
                onClick={handleSave}
                disabled={isSaving}
                className="bg-[#1db954] hover:bg-[#1ed760] disabled:bg-zinc-700 disabled:cursor-not-allowed text-black font-semibold px-4 py-2 rounded-full text-sm transition-colors"
              >
                {isSaving ? 'Saving…' : 'Save to Spotify'}
              </button>
            </>
          )}
        </div>
      </header>

      {/* Body */}
      <div className="flex-1 flex overflow-hidden">
        {/* Track list */}
        <div className="flex-1 overflow-y-auto min-w-0 scroll-thin">
          <TrackList tracks={data.tracks} onRemove={handleRemove} />
        </div>

        {/* Tune panel */}
        <div className="w-72 shrink-0 border-l border-zinc-800 flex flex-col overflow-hidden">
          <TunePanel
            tracks={data.tracks}
            audioFeatures={data.audioFeatures}
            chatHistory={chatHistory}
            isTuning={isTuning}
            onTune={handleTune}
          />
        </div>
      </div>
    </div>
  );
}

function formatTargets(targets: AudioFeatureTargets | null): string {
  if (!targets) return 'Adjust audio features';
  const parts = Object.entries(targets).map(([k, v]) => {
    if (k === 'tempo') return `tempo → ${Math.round(v as number)} bpm`;
    const labels: Record<string, string> = { energy: 'energy', danceability: 'danceability', valence: 'mood' };
    return `${labels[k] ?? k} → ${(v as number).toFixed(2)}`;
  });
  return `Set ${parts.join(', ')}`;
}
